### ISSUE TITLE
New Release Please

### ISSUE THREAD

**Issue by md-5** [tcurdt/jdependency#11]
Hi,

Would greatly appreciate a release of the latest version to central.
I understand that a beta version of asm is being used, but Java 9 support for maven-shade-plugin is blocked on this, and subsequently so are even further downstream projects.

Thanks

**Comment by don-vip** [comment]
a lot of people are waiting, the release is expected on Sunday, see https://github.com/tcurdt/jdependency/pull/10#issuecomment-320510884

**Comment by md-5** [comment]
Thanks, will close as such.

**Comment by tcurdt** [comment]
Hm - I just realized ASM has no version 6 release yet. That's a problem.

**Comment by don-vip** [comment]
Maybe you can release a "1.2-beta" version?

**Comment by tcurdt** [comment]
That's a cascading problem then :)

Did anyone check with the ASM peeps about the 6.0 release yet? Do they have a date yet?

If there is no release soon I guess the best course of action is to inline the dependencies with the shade plugin on `jdependency` itself. Then I am OK to release with the ASM beta.

**Comment by tcurdt** [comment]
Hm. I am getting
```
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:201)
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:132)
	at org.apache.maven.plugins.shade.filter.MinijarFilter.addDependencyToClasspath(MinijarFilter.java:118)
	at org.apache.maven.plugins.shade.filter.MinijarFilter.<init>(MinijarFilter.java:99)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.getFilters(ShadeMojo.java:814)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:446)
	... 22 more
```
Which smells a bit like a chicken and egg problem.

**Comment by don-vip** [comment]
Maven shade depends on you ;)
@forax any news on the release date of ASM6 final?

**Comment by forax** [comment]
ASM6 final will be released at the same time as the JDK 9.

ASM6 beta which is in sync with the java 9 VM spec is available on Maven Central,
see https://mail.ow2.org/wws/arc/asm/2017-08/msg00000.html

**Comment by tcurdt** [comment]
OK. I am not really fond of releasing with (or more specifically exposing) a beta dependency - but seems like there isn't really a good way around it at the moment. So here is what I would suggest:

1. I'll release 1.2 with the beta dependency.
2. Then the maven shade plugin can be released using 1.2 and the ASM6 beta.
3. I'll then use new maven shade plugin to release 1.3 soon after. It will no longer expose any transitive dependencies.
4. Then a new maven shade plugin can be released using 1.3.

That should decouple things and hopefully everyone is happy.
Does that sound like a plan?

**Comment by forax** [comment]
If it can help your conscience, here are the rules for naming the release of ASM.

ASM uses tagged branches, for features of next release (by example, constant dynamic that will be introduced or not in the JDK 10 [1]).
ASM uses ALPHA for features that are in the preview of the JVM spec, the API can change.
ASM uses BETA for features of the JVM spec that have been voted by the JCP and the API is freezed.
ASM uses RELEASE for features that have been published in the JVM spec.

And all API additions are always backward compatible.

[1] https://gitlab.ow2.org/asm/asm/tree/CONDY

**Comment by tcurdt** [comment]
✓ 1.2 is released - just waiting for it to show up in central

If the shade plugin or ASM has a new release - please let me know.

**Comment by don-vip** [comment]
@rfscholte this is for you :)

**Comment by md-5** [comment]
Thanks mate.
Fwiw the shade plugin works in projects now if you add a <dependency> section in your own pom to make it use 1.2 for the build, no code changes required.

As stated above asm beta is in step with the frozen java spec, so not expecting firther issues.

Thanks

**Comment by rfscholte** [comment]
Thanks, I think all is there to release a new version of maven-shade-plugin. If so, I'll prepare a release within a week.

**Comment by rfscholte** [comment]
Maven Shade Plugin 3.1.0 now available at Central. Thank you all for the cooperation!

**Comment by tcurdt** [comment]
@rfscholte did a quick test and it works great :)

...but I think I might have found a problem:
It stills lists commons-io in the META-INF - surprisingly not ASM though.

I will try to have a closer look later this week and then release 1.3
