### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by khmarbaise** [tcurdt/jdependency#134]
Hi, would it be possible to make a new release ?

**Comment by tcurdt** [comment]
I've already started to prepare one - but got distracted :)

**Comment by tcurdt** [comment]
Anything particular you want included? Or just dep updates?

**Comment by khmarbaise** [comment]
I just wanted to have an upgraded release with most recent versions of asm etc. That would be great. No problem.

**Comment by tcurdt** [comment]
released! only waiting for central to sync

**Comment by khmarbaise** [comment]
Many thanks for your help.
