### ISSUE TITLE
Release 1.5 to maven central

### ISSUE THREAD

**Issue by julianojulio** [tcurdt/jdependency#18]
Hi,

Would it be possible to release version 1.5 to Maven Central?
The fix implemented on #17 should unblock [maven-shaded-plugin](https://issues.apache.org/jira/browse/MSHADE-289).

Thanks

**Comment by tcurdt** [comment]
I am on it. Just noticed a problem in the tests that needs to be fixed first.

**Comment by tcurdt** [comment]
The next release will be 2.0 because I am raising the java source compatibility to java8.

Binary wise it will probably will also work with older version - but I don't really want to be bothered with those.

Will that be a problem?

**Comment by julianojulio** [comment]
I don't think it will be a problem. @rfscholte [is aware of that](https://issues.apache.org/jira/browse/MSHADE-289?focusedCommentId=16548022&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16548022) and he said this would only impact clients requiring the `minimizeJar` feature of the plugin.

**Comment by tcurdt** [comment]
I assume for people still on java6 there isn't really a need for an update anyway.

**Comment by tcurdt** [comment]
Just released 2.0 to maven central. Give it a few minutes for the sync.
