### ISSUE TITLE
Upgrade asm to 8.0

### ISSUE THREAD

**Issue by khmarbaise** [tcurdt/jdependency#27]
https://search.maven.org/search?q=org.ow2.asm

Could you so kind to upgrade asm to 8.0 and make a new release ? Would be great. thanks in advance.

**Comment by tcurdt** [comment]
I was about the release 2.4.0 with 7.3.1. But maven central is currently refusing to take the bundle from me. I get a permission error. I've talked to sontatype and waiting to hear back from them.

I guess in the meantime I'll try the upgrade to asm 8 then :)

**Comment by tcurdt** [comment]
All prepared for a release of 2.4.0 with asm8 - just waiting for the maven central folks to get back to me.

**Comment by tcurdt** [comment]
released! now just waiting for the maven central sync.
