### ISSUE TITLE
jdependency shows wrong class clash

### ISSUE THREAD

**Issue by CLandsberg** [tcurdt/jdependency#47]
Hello,
There is a bug in the jdependency, where a class is wrongly linked to a wrong jar!

Code to reproduce (it is from a gradle buildscript)
```
      final Clazzpath cp = new Clazzpath();

      cp.addClazzpathUnit(new File("$jarDir/cxf-core-3.4.0.jar"), 'cxf-core-3.4.0.jar');
      cp.addClazzpathUnit(new File("$jarDir/woodstox-core-6.2.3.jar"), 'woodstox-core-6.2.3.jar');

      cp.getClazzes().stream()
        .filter{ it.getName().contains('W3CSchema')}
        .forEach{println "$it -> ${it.getClazzpathUnits()}"}
```

output:
```
> Task :checkClasspath
com.ctc.wstx.msv.W3CSchemaFactory -> [woodstox-core-6.2.3.jar]
com.ctc.wstx.msv.W3CSchema -> [cxf-core-3.4.0.jar, woodstox-core-6.2.3.jar]
com.ctc.wstx.osgi.ValidationSchemaFactoryProviderImpl$W3CSchema -> [woodstox-core-6.2.3.jar]
```

But this is wrong, cxf-core-3.4.0.jar does not contain W3CSchema nor any 'com'-package.

link to the libs:
https://mvnrepository.com/artifact/org.apache.cxf/cxf-core/3.4.0
https://mvnrepository.com/artifact/com.fasterxml.woodstox/woodstox-core/6.2.3

kind regards

ps. there are many more false results with different classes with this two jars, as well with other jars

**Comment by tcurdt** [comment]
Thanks for the report. I've turned it into a testcase and can reproduce it. I even have a fix for it already.
But I am surprised this never has been reported. And I am afraid I am missing something.
I'll have another second look tomorrow.

**Comment by tcurdt** [comment]
@CLandsberg If you could cross check master that would be great.

**Comment by CLandsberg** [comment]
@tcurdt thank you for the fast response.
Version 2.6.0 fixed the false positives. Thank you for the fix and keep up the good work.

Viele Grüße
Clemens

**Comment by CLandsberg** [comment]
Hello @tcurdt ,
I would like to ask you, when you plan to release Version 2.6.0.

viele grüße
Clemens

**Comment by tcurdt** [comment]
Ideally? Two months ago. I wanted to get the release process streamlined.

https://github.com/tcurdt/jdependency/blob/master/.github/workflows/release-ossrh.yml

And I didn't get around to test and fix it yet. That's the only thing holding back the release.

**Comment by tcurdt** [comment]
@CLandsberg if you want to help - it would be great to have a second set of eyes. The signing is currently still failing.

https://github.com/tcurdt/jdependency/blob/master/.github/workflows/release-ossrh.yml
https://github.com/actions/setup-java/issues/120

**Comment by tcurdt** [comment]
@CLandsberg it's released
