### ISSUE TITLE
Missing classes from JRE

### ISSUE THREAD

**Issue by CLandsberg** [tcurdt/jdependency#50]
Hallo,
i just tried the feature with missing classes. When i uses it it shows some classes from JRE missing, for example:
...
com.sun.net.httpserver.Filter referenced by [org.springframework.remoting.support.SimpleHttpServerFactoryBean, org.springframework.remoting.jaxws.SimpleHttpServerJaxWsServiceExporter][[spring-context-5.0.8.RELEASE.jar, spring-web-5.0.8.RELEASE.jar]]
com.sun.net.httpserver.Headers referenced by [org.springframework.remoting.httpinvoker.SimpleHttpInvokerServiceExporter, org.springframework.remoting.caucho.SimpleHessianServiceExporter][[spring-web-5.0.8.RELEASE.jar]]
com.sun.net.httpserver.HttpContext referenced by [org.springframework.remoting.support.SimpleHttpServerFactoryBean, org.springframework.remoting.jaxws.SimpleHttpServerJaxWsServiceExporter][[spring-context-5.0.8.RELEASE.jar, spring-web-5.0.8.RELEASE.jar]]
...
com.sun.net.ssl.KeyManager referenced by [oracle.security.pki.ssl.ClassFileServer, oracle.security.pki.ssl.SSLSocketClient, oracle.security.pki.ssl.OracleSSLX509KeyManagerFactory103][[oraclepki-12.1.0.2.jar]]
com.sun.net.ssl.KeyManagerFactory referenced by [oracle.security.pki.ssl.ClassFileServer, oracle.security.pki.ssl.SSLSocketClient][[oraclepki-12.1.0.2.jar]]
com.sun.net.ssl.KeyManagerFactorySpi referenced by [oracle.security.pki.ssl.OracleSSLX509KeyManagerFactory103][[oraclepki-12.1.0.2.jar]]
...
sun.security.krb5.Checksum referenced by [oracle.net.ano.AuthenticationService][[ojdbc7-12.1.0.2.jar]]
sun.security.krb5.EncryptedData referenced by [oracle.net.ano.AuthenticationService][[ojdbc7-12.1.0.2.jar]]
sun.security.krb5.EncryptionKey referenced by [oracle.net.ano.AuthenticationService][[ojdbc7-12.1.0.2.jar]]
...

Do i need to add the JRE to classpath? This is not trivial with the new jrt-fs. On the other hand, basic java classes are not marked missing.

greetings

**Comment by tcurdt** [comment]
Have a look at the testcase. Sorry, for the lack of a link. Just on my mobile.

**Comment by CLandsberg** [comment]
I checked the testcases and they are not applicable.

The library differs between JRE dependencies (e.g. java.lang.String etc.) and other Dependencies.
No test explicitly adds the JRE to dependencies. but String is not listed as missing.

Some other packages (a wild guess, that the package name is responsible) are also part of the JRE (e.g com.sun.net.httpserver) but they are marked as missing. I find no filter on packages in this project directly, so i guess this is done by ASM?

**Comment by tcurdt** [comment]
This is the applicable test case.

  https://github.com/tcurdt/jdependency/blob/master/src/test/java/org/vafer/jdependency/ClazzpathTestCase.java#L194

There is no magic about the JRE. So it is kind of expected that `java.` and 'sun.` packages can be ignored.
I am actually surprised if `java.lang` does appear in there. But it's been a while since I wrote all that code.

What you could do is actually read the `rt.jar`and remove those classes.
But honestly - I don't think the runtime changes that much that and some manual exclusion will probably be fine.

**Comment by tcurdt** [comment]
So to summarize: I think it works as expected.

**Comment by CLandsberg** [comment]
The JRE contains many more packages then java. and sun. And some sun. packages are not included in the jre,

new version of java (starting with java 9) does not contain a rt.jar anymore but a rt-fs,jar which is a virtual filesystem.

To check all packages in the JRE:

```
FileSystem fs = FileSystems.getFileSystem(URI.create("jrt:/"));
		Set<String> jrePackages = new HashSet<>(2048);
		for (var d: fs.getRootDirectories()) {
			try (var files = Files.walk(d)){
				files
					.filter(Files::isRegularFile)
					.filter(file -> !file.endsWith("module-info.class") && file.getFileName().toString().endsWith(".class"))
				.filter(file -> Files.isRegularFile(file) && file.getFileName().toString().endsWith(".class"))
				.forEach(clazz -> {
					var packageName = clazz.subpath(2, clazz.getNameCount()-1).toString();
					jrePackages.add(packageName);
				});
			}
		}
```

Feel free to include it in a helper class
