### ISSUE TITLE
Nontrivial assumption in addClazzpathUnit

### ISSUE THREAD

**Issue by superbobry** [tcurdt/jdependency#9]
It seems that `addClazzpathUnit` expects that all dependencies of the class were already added. A simple test case demonstrating the issue on the `jdependency` sources:

```java
public class AddCpuTest {
    @Test
    public void testClassThenDependency() throws IOException {
        Clazzpath cp = new Clazzpath();
        ClazzpathUnit cpu = cp.addClazzpathUnit(getLocalClassFile(Clazzpath.class));
        cp.addClazzpathUnit(getLocalClassFile(DependenciesClassAdapter.class));
        assertFalse(cpu.getDependencies().isEmpty());
    }

    @Test
    public void testDependencyThenClass() throws IOException {
        Clazzpath cp = new Clazzpath();
        cp.addClazzpathUnit(getLocalClassFile(DependenciesClassAdapter.class));
        ClazzpathUnit cpu = cp.addClazzpathUnit(getLocalClassFile(Clazzpath.class));
        assertFalse(cpu.getDependencies().isEmpty());
    }

    private File getLocalClassFile(Class<?> clazz) {
        URL url = clazz.getResource('/' + clazz.getName().replace('.', '/') + ".class");
        return new File(url.getFile());
    }
}
```

Is this the expected behaviour?

**Comment by superbobry** [comment]
Oh, right, the method is not suited for adding a single class file. My question is then, why not allow that?

**Comment by tcurdt** [comment]
@superbobry right now it pretty much expects a collection of classes from a jar inputstream

https://github.com/tcurdt/jdependency/blob/master/src/main/java/org/vafer/jdependency/Clazzpath.java#L86

It certainly could be (rather simply) changed to support single class files.

**Comment by tcurdt** [comment]
As for your testcases - I am not quite sure what you are trying to show with them.

**Comment by superbobry** [comment]
Thanks for a quick reply. The method you've linked to is exactly what I need.

As for the tests, these were written with wrong assumptions about the API, just ignore them.
